FROM python:3.13.9-slim

WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY pyproject.toml uv.lock* /app/

RUN uv sync --frozen

COPY . /app/

EXPOSE 7086

ARG RUN_MODE=dev
ENV RUN_MODE=${RUN_MODE}

COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
